from django.contrib import admin
from django.urls import path
from api.views import (
    health_check,
    me,
    login,
    doctor_list,
    patient_list,
    patient_detail,
    patient_search,
    ai_predict,
    ai_gradcam,
    ai_image_analyze,
    media_local,
    media_gcs,
    patient_media_upload,
    bookmark_detail,
    bookmark_list,
    consultation_list,
    consultation_detail,
    consultation_status_update,
    consultation_mark_read,
    consultation_complete,
    chat_room_list_create,
    chat_message_list_create,
    chat_room_mark_read,
    chat_message_resource_status,
    memo_list_create,
    memo_detail,
    voice_memo_create,
    memo_audio,
    notification_list,
    notification_mark_read,
    EMRSignOffListCreateView,
    EMRSignOffDetailView,
    emr_signoff_report,
    emr_signoff_transmit,
    kakao_login,
    kakao_signup,
    exam_ai_run_and_persist,
    appointment_list,
    appointment_me,
    appointment_detail,
)

from api.gpt_views import (
    GPTTestView,
    ChatAPIView,
)
from api.chatbot_session_views import (
    chatbot_session_list,
    chatbot_session_detail,
)

from rest_framework_simplejwt.views import(
    TokenObtainPairView,
    TokenRefreshView,
)
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/health/", health_check),
    path("api/login/", login),    
    path("api/auth/kakao/login/", kakao_login),
    path("api/auth/kakao/signup/", kakao_signup),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/me/", me),
    path("api/doctors/", doctor_list),
    path("api/patients/", patient_list),
    path("api/patients/search/", patient_search),
    path("api/patients/<str:patient_id>/media/", patient_media_upload),
    path("api/patients/<str:patient_id>/", patient_detail),
    path("api/bookmarks/", bookmark_list),
    path("api/bookmarks/<int:bookmark_id>/", bookmark_detail),
    path(
        "api/emr-signoffs/",
        EMRSignOffListCreateView.as_view(),
        name="emr-signoff-list",
    ),
    path(
        "api/emr-signoffs/<int:pk>/",
        EMRSignOffDetailView.as_view(),
        name="emr-signoff-detail",
    ),
    path(
        "api/emr-signoffs/<int:pk>/report/",
        emr_signoff_report,
        name="emr-signoff-report",
    ),
    path(
        "api/emr-signoffs/<int:pk>/transmit/",
        emr_signoff_transmit,
        name="emr-signoff-transmit",
    ),
    path("api/appointments/", appointment_list),
    path("api/appointments/me/", appointment_me),
    path("api/appointments/<int:appointment_id>/", appointment_detail),
    path("api/consultations/", consultation_list),
    path("api/consultations/<int:consultation_id>/", consultation_detail,),
    path("api/consultations/<int:consultation_id>/status/", consultation_status_update,),
    path("api/consultations/<int:consultation_id>/read/", consultation_mark_read),
    path("api/consultations/<int:consultation_id>/complete/", consultation_complete),
    path("api/chat/rooms/", chat_room_list_create),
    path("api/chat/rooms/<int:room_id>/messages/", chat_message_list_create),
    path("api/chat/rooms/<int:room_id>/read/", chat_room_mark_read),
    path("api/chat/messages/<int:message_id>/resource-status/", chat_message_resource_status),
    path("api/memos/", memo_list_create),
    path("api/memos/voice/", voice_memo_create),
    path("api/memos/<int:memo_id>/", memo_detail),
    path("api/memos/<int:memo_id>/audio/", memo_audio),
    path("api/notifications/", notification_list),
    path("api/notifications/<int:notification_id>/read/", notification_mark_read),
    path("api/media/local/", media_local),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path("api/ai/predict/", ai_predict),
    path("api/ai/gradcam/", ai_gradcam),
    path("api/ai/image-analyze/", ai_image_analyze),
    path("api/media/gcs/", media_gcs),
    path("api/exams/<int:exam_id>/ai/run/", exam_ai_run_and_persist),
    path("gpt-test/", GPTTestView.as_view()),
    path("chat/", ChatAPIView.as_view()),
    path("api/chatbot/sessions/", chatbot_session_list),
    path(
        "api/chatbot/sessions/<int:session_id>/",
        chatbot_session_detail,
    ),
]
